#!/bin/bash/python3
import os
import py_compile

# Get the filename from the environment variable
filename = os.environ.get('PYFILE')

# Compile the file
py_compile.compile(filename)

# Rename the compiled file with the .pyc extension
new_filename = filename + 'c'
os.rename('__pycache__/' + filename + '.cpython-38.pyc', new_filename)

print(f'Compiled {filename} to {new_filename}')
